framework:
    secret: '%env(APP_SECRET)%'
    serializer:
        enabled: true
        mapping:
            paths: ['%kernel.project_dir%/config/mappings/serialization/App']
    validation:
        enabled: true
        mapping:
            paths: ['%kernel.project_dir%/config/mappings/validation/App']
    php_errors:
        log: true
