security:
    encoders:
        App\Entity\User:
            algorithm: 'bcrypt'

    providers:
        app_provider:
            entity:
                class: 'App\Entity\User'
                property: 'email'

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    firewalls:
        dev:
            pattern: '^/(_(profiler|wdt)|css|images|js)/'
            security: false
        login:
            pattern:  '^/login'
            stateless: true
            anonymous: true
            json_login:
                check_path:               '/login_check'
                success_handler:          'lexik_jwt_authentication.handler.authentication_success'
                failure_handler:          'lexik_jwt_authentication.handler.authentication_failure'
                require_previous_session: false
        api:
            pattern:   '^/'
            stateless: true
            anonymous: true
            lexik_jwt: ~

    access_control:
        - { path: '^/warehouses', role: 'ROLE_ADMIN' }
        - { path: '^/', roles: 'IS_AUTHENTICATED_ANONYMOUSLY' }