app:
    resource: '../src/Action/'
    type: 'annotation'

# config the login route for the swagger ui
app_user_login:
    path: '/users/login'
    defaults: { _api_resource_class: 'App\Entity\User', _api_collection_cperation_name: 'login' }