parameters:
    locale: 'de'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests}'

    App\Action\:
        resource: '../src/Action'
        tags: ['controller.service_arguments']

    # Extension to filter disabled products in every api endpoint
    App\Extension\ActiveProductExtension:
        tags:
            - { name: 'api_platform.doctrine.orm.query_extension.collection', priority: 9 }