resources:
    App\Entity\Product:
        attributes:
            normalization_context: { groups: ['product_view'] }
            filters: ['product.search_filter']
            pagination_client_enabled: true
            client_items_per_page: true
            pagination_items_per_page: 50
        collectionOperations:
            get:
                method: 'GET'
                normalization_context: { groups: ['product_list'] }
            api_categories_products_get_subresource:
                method: 'GET'
                normalization_context: { groups: ['product_list'] }
        itemOperations:
            get:
                method: 'GET'
            delete:
                method: 'DELETE'
                access_control: is_granted('ROLE_ADMIN')
    App\Entity\Warehouse:
        attributes:
            denormalization_context: { groups: ['warehouse_write'] }
    App\Entity\Category:
        attributes:
            pagination_enabled: false
        properties:
            products:
                subresource: { collection: true, resourceClass: 'App\Entity\Product' }
        attributes:
            denormalization_context: { groups: ['category_write'] }